server:
  port:
    84

spring:
  application:
    name:
      nacos-sentinel-feign-consumer
  cloud:
    nacos:
      discovery:
        server-addr:
          localhost:8848
    sentinel:
      transport:
        dashboard:
          localhost:8080
        port:
          8719

service-url:
  nacos-user-service: http://cloud-nacos-sentinel-feign-payment

feign:
  sentinel:
    enabled:
      true
