server:
  port:
    8003

spring:
  application:
    name:
      cloud-payment-service
  datasource:
    type:
      com.alibaba.druid.pool.DruidDataSource
    driver-class-name:
      com.mysql.jdbc.Driver
    url:
      jdbc:mysql://localhost:3306/payment?useSSL=false&useUnicode=true&characterEncoding=utf8
    username:
      root
    password:
      root
  resources:
    static-locations:classpath:/templates/
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181


mybatis:
  config-locations:
    classpath:mybatis/mybatis-config.xml
  mapper-locations:
    classpath:mybatis/mapper/*.xml
  type-aliases-package:
    com.atguigu.springcloud.entities
