server:
  port:
    8005

spring:
  application:
    name:
      cloud-hystrix-payment-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: payment8005
    prefer-ip-address: true

#management:
#  endpoints:
#    web:
#      exposure:
#        include:
#          "*"
