server:
  port:
    80
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone:
        http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
spring:
  application:
    name:
      feign-consumer-feign-hystrix-order

#ribbon:
#  ReadTimeout:
#    5000
#  ConnectTimeOut:
#    5000
logging:
  level:
    com.atguigu.springcloud.service.FeignPaymentService:
      debug

feign:
  hystrix:
    enabled:
      true
